#!/bin/bash/

#1
apt-get update
apt-get install gcc
apt-get install make
apt-get install libncurses-dev
#add
apt-get install rpm

#2
tar -xvf /vagrant/bastet-0_41.tar
cd /vagrant/bastet-0.41
vim config.h #editing config
make
make install

#3
dpkg --get-selections | grep -v deinstall | awk '{print $1}' > /task3.log
#4
apt-cache rdepends gcc > /task4.log

#5
cd ~
mkdir localrepo && cd ~/localrepo/
apt-get --download-only install checkinstall
cp /var/cache/apt/archives/checkinstall_1.6.2-3ubuntu1_i386.deb /root/localrepo/
apt-get install dpkg-dev
## created repo list script  vim ~/localrepo/update-mydebs
chmod u+x ~/localrepo/update-mydebs
./update-mydebs 
#dpkg-scanpackages: info: Wrote 1 entries to output Packages file.
# changed /etc/apt/sources.list

#6
apt-cache policy > /task6.log 

#7
# comment all vim /etc/apt/sources.list
apt-cache policy  
# 500 file:/root/localrepo/ ./ Packages

#8
cp /vagrant/fortunes-ru_1_52-2_all.deb /root/localrepo/
./update-mydebs 
apt-get update
apt-get install fortunes-ru
# need to get deps. The easiest way is to uncomment repos back
apt-get update
apt-get install fortunes-ru