.TH BASTET 6 "MAY 2004"
.SH NAME
bastet \- frustrating tetris clone with an evil AI
.SH SYNOPSIS
.B bastet [WIDTHxHEIGHT]
.SH DESCRIPTION
.B bastet
(stands for "bastard tetris") is a free clone of Tetris(r) (built on the top 
of petris by Peter Seidler) designed to be "as bastard as possible": every 
turn it calculates the worst possible block to provide, guaranteeing endless 
frustration.
.SH USAGE
Use up and down arrow to select a level (=block speed. The higher the level,
the more points you will get when you drop a brick).
Use left and right arrow to move the piece from side to side. Use up arrow 
to rotate, and down arrow to speed up the fall.

Some other keybindings that will be useful: p for pausing, q for quitting 
during the game, space to drop current block, 0 to rotate the block CCW.

Note that the block preview does not work as in normal tetris: instead,
it display the most useful brick, the one you would like to have. Needless
to say, you will never get it! 

.SH OPTIONS
.IP -h
Display the format for setting width and height of the playing area.
.SH FILES
.I /var/games/bastet.scores
.RS
The global high scores for bastet. 
.SH BUGS
None known at the moment. If you find one, please report it to the author.
.SH AUTHOR


